# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-07 09:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='snippet',
            old_name='hihglighted',
            new_name='highlighted',
        ),
    ]
